export const projects = [
  {
    id: "portal",
    number: "01",
    navTitle: "Портал",
    eyebrow: "Учебный VFX-эксперимент",
    title: "Переход между мирами",
    lead: "Сначала — работа внутри кадра. Затем её энергия становится переходом всей страницы.",
    contribution: "VFX · частицы · 3D-композитинг · трекинг",
    task: "Встроить фантастический портал в реальную сцену с учётом перспективы, света и глубины.",
    result: "Эффект воспринимается частью пространства, а не наложенной поверх видео графикой.",
    tech: "Fusion: pEmitter, pTurbulence, Camera3D, PointCloud3D, GroundPlane, Glow и финальный композитинг.",
    accent: "cyan",
    format: "16:9",
    media: {
      kind: "single",
      src: "./media/clips/portal.m4v",
      label: "Портал, созданный Евгением в DaVinci Resolve Fusion",
    },
  },
  {
    id: "buzz",
    number: "02",
    navTitle: "Buzz",
    eyebrow: "Работа из портфолио",
    title: "34 секунды до действия",
    lead: "Короткий англоязычный Reels объясняет сервис аренды пауэрбанков и ведёт к ближайшей станции.",
    contribution: "Монтаж · кинетическая типографика · motion · звук",
    task: "Познакомить зрителя с основателем и быстро объяснить механику сервиса.",
    result: "Одна вертикальная история: батарея, карта Нидерландов, 600 локаций и ясный финальный призыв.",
    tech: "Формат 9:16, 34 секунды. DaVinci Resolve: монтаж, фирменная графика, цвет и саунд-дизайн.",
    accent: "coral",
    format: "9:16",
    media: {
      kind: "single",
      src: "./media/clips/buzz.m4v",
      label: "Фрагмент рекламного Reels для Buzz Powerbanks",
      layout: "portrait",
    },
  },
  {
    id: "football",
    number: "03",
    navTitle: "Масштаб",
    eyebrow: "Работа из портфолио",
    title: "250 ГБ. Шесть матчей. Одна история.",
    lead: "Большой игровой день превращён в динамичную выжимку без потери масштаба и атмосферы турнира.",
    contribution: "Мультикам · синхронизация · цвет · Fairlight",
    task: "Систематизировать материал с разных камер и собрать шесть полноценных игр.",
    result: "Финальный ролик показывает масштаб проекта и лучшие моменты игрового дня.",
    tech: "DaVinci Resolve Studio: Edit, Color и Fairlight. Обработка разных экспозиций и выравнивание звука.",
    accent: "ice",
    format: "16:9",
    media: {
      kind: "single",
      src: "./media/clips/football.m4v",
      label: "Фрагмент итогового ролика футбольного турнира",
    },
  },
  {
    id: "story",
    number: "04",
    navTitle: "История",
    eyebrow: "Трейлеры · музыка · ритм",
    title: "Монтаж, который слышит историю",
    lead: "Мрачная интернет-легенда, короткометражное кино и музыкальный клип — три разных ритма повествования.",
    contribution: "Драматургия · трейлерный монтаж · музыка · SFX",
    task: "Собрать разрозненные кадры в истории, которые удерживают внимание и не пересказывают всё заранее.",
    result: "Каждый ролик получает собственное напряжение, паузы, темп и визуальный характер.",
    tech: "DaVinci Resolve Studio: Edit, Color, Fairlight; титры, переходы, озвучка и музыкальное оформление.",
    accent: "velvet",
    format: "16:9",
    media: {
      kind: "single",
      src: "./media/clips/story.m4v",
      label: "Фрагмент трейлера Disturbing Internet Legends",
    },
  },
  {
    id: "vfx",
    number: "05",
    navTitle: "VFX Lab",
    eyebrow: "Учебные VFX-эксперименты",
    title: "Кадр перестаёт быть плоским",
    lead: "Свет автомобиля, разрушение здания, Magic Mask и цветовая волна — короткая лаборатория превращений.",
    contribution: "Fusion · композитинг · маски · цвет",
    task: "Встроить эффекты так, чтобы они подчинялись свету, движению и перспективе исходной сцены.",
    result: "Технические упражнения читаются как единая подборка, но каждый приём остаётся понятным.",
    tech: "Magic Mask, Planar Tracker, Qualifier, частицы, Glow, Light Rays, ноды Fusion и контроль по scopes.",
    accent: "ember",
    format: "LAB",
    media: {
      kind: "mosaic",
      items: [
        { src: "./media/clips/vfx-auto.m4v", label: "Световые эффекты для автомобиля" },
        { src: "./media/clips/vfx-building.m4v", label: "VFX-разрушение здания" },
        { src: "./media/clips/vfx-bear.m4v", label: "Surface Tracking на движущемся объекте" },
      ],
    },
  },
];

export const filmstripItems = [
  { id: "hero", number: "00", title: "FRAME ZERO" },
  ...projects.map(({ id, number, navTitle: title }) => ({ id, number, title })),
  { id: "formats", number: "06", title: "Форматы" },
  { id: "author", number: "07", title: "Tim Cut" },
  { id: "final", number: "08", title: "Финал" },
];
